// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// jumps_from_map
NumericVector jumps_from_map(const NumericVector& map, const double& lambda);
RcppExport SEXP simulate_jumps_from_map(SEXP mapSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type map(mapSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(jumps_from_map(map, lambda));
    return rcpp_result_gen;
END_RCPP
}
// ancestry_chunks
LogicalVector ancestry_chunks(const NumericVector& jumps);
RcppExport SEXP simulate_ancestry_chunks(SEXP jumpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type jumps(jumpsSEXP);
    rcpp_result_gen = Rcpp::wrap(ancestry_chunks(jumps));
    return rcpp_result_gen;
END_RCPP
}
// generate_hybrid_cpp
NumericVector generate_hybrid_cpp(const NumericMatrix& H1, const NumericMatrix& H2, const double alpha, const LogicalVector chunks);
RcppExport SEXP simulate_generate_hybrid_cpp(SEXP H1SEXP, SEXP H2SEXP, SEXP alphaSEXP, SEXP chunksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type H1(H1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type H2(H2SEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const LogicalVector >::type chunks(chunksSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_hybrid_cpp(H1, H2, alpha, chunks));
    return rcpp_result_gen;
END_RCPP
}
// haplo_to_geno
NumericMatrix haplo_to_geno(const NumericMatrix& H);
RcppExport SEXP simulate_haplo_to_geno(SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(haplo_to_geno(H));
    return rcpp_result_gen;
END_RCPP
}
