# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' 
jumps_from_map <- function(map, lambda) {
    .Call('simulate_jumps_from_map', PACKAGE = 'simulate', map, lambda)
}

#' @export
#' 
ancestry_chunks <- function(jumps) {
    .Call('simulate_ancestry_chunks', PACKAGE = 'simulate', jumps)
}

#' @export
#' 
generate_hybrid_cpp <- function(H1, H2, alpha, chunks) {
    .Call('simulate_generate_hybrid_cpp', PACKAGE = 'simulate', H1, H2, alpha, chunks)
}

#' @export
#' 
haplo_to_geno <- function(H) {
    .Call('simulate_haplo_to_geno', PACKAGE = 'simulate', H)
}

